# Site settings
name: wings27-blog
title: Wings27 Blog
SEOTitle: Wings27 Blog | Practice makes perfect.
header-img: img/home-bg.jpg
email: wenqs27@gmail.com
description: "Practice makes perfect."
keyword: "IT, Programmer, Blog, Wings27"
url: "http://wings27.github.io"



# SNS settings
RSS: true
github_username:    wings27
facebook_username:  wenqiushi
zhihu_username:     wings27



# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","*.sh","*.enc"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

gems: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: wings27blog           # uncomment to use.

# gitalk settings
gitalk_clientID: e5628fa1ccbd73e37aae           # uncomment to use.
gitalk_clientSecret: da2e70105d96059f6ac9f0c20aafa0bfbd98f45e

# Duoshuo settings
# duoshuo_username: wings27blog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing



# Analytics settings
# Baidu Analytics
ba_track_id: 120193a1e238d1cf4ef681306cde929b
# Google Analytics
ga_track_id: 'UA-80662619-1'            # Format: UA-xxxxxx-xx
ga_domain: wings27.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Love cooking and coding."
sidebar-avatar: /img/avatar-wings.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Zhihu",
        href: "http://www.zhihu.com"
    }
]
